import { useEffect, useMemo, useState } from 'react'
import { isSupabaseConfigured, readTable, supabase, type DbRow } from './lib/supabase'
import { dayNames, previewLessons, previewMeals, previewSports, type Day, type Lesson, type Meal, type Sport } from './data/preview'
import './styles.css'

type Tab = 'oggi' | 'calendario' | 'alimentazione' | 'allenamenti' | 'esami' | 'progressi'
const tabs: { id: Tab; label: string; icon: string }[] = [
  { id: 'oggi', label: 'Oggi', icon: '✦' }, { id: 'calendario', label: 'Calendario', icon: '▦' }, { id: 'alimentazione', label: 'Alimentazione', icon: '◒' }, { id: 'allenamenti', label: 'Allenamenti', icon: '↗' }, { id: 'esami', label: 'Esami', icon: '□' }, { id: 'progressi', label: 'Profilo', icon: '◎' },
]
const asString = (row: DbRow, ...keys: string[]) => keys.map(k => row[k]).find(v => v !== undefined && v !== null) as string | undefined
const asNum = (row: DbRow, ...keys: string[]) => Number(asString(row, ...keys) ?? 0)
function localDay(timezone: string) { try { return Number(new Intl.DateTimeFormat('en-US', { weekday: 'short', timeZone: timezone }).format(new Date()).replace('Sun', '0').replace('Mon', '1').replace('Tue', '2').replace('Wed', '3').replace('Thu', '4').replace('Fri', '5').replace('Sat', '6')) as Day } catch { return new Date().getDay() as Day } }

export default function App() {
  const [tab, setTab] = useState<Tab>('oggi')
  const [day, setDay] = useState<Day>(localDay('Europe/Rome'))
  const [session, setSession] = useState<unknown>(null)
  const [email, setEmail] = useState('')
  const [message, setMessage] = useState('')
  const [loading, setLoading] = useState(isSupabaseConfigured)
  const [profile, setProfile] = useState<DbRow | null>(null)
  const [lessons, setLessons] = useState<Lesson[]>(previewLessons)
  const [meals, setMeals] = useState<Record<Day, Meal[]>>(previewMeals)
  const [sports, setSports] = useState<Sport[]>(previewSports)
  const [exams, setExams] = useState<DbRow[]>([])
  const [tracking, setTracking] = useState<DbRow[]>([])

  useEffect(() => { if (!supabase) { setLoading(false); return }; supabase.auth.getSession().then(({ data }) => { setSession(data.session); setLoading(false) }); const { data } = supabase.auth.onAuthStateChange((_event, next) => setSession(next)); return () => data.subscription.unsubscribe() }, [])
  useEffect(() => { if (!supabase || !session) return; let active = true; (async () => { const [p, l, n, s, e, t] = await Promise.all([readTable('profiles'), readTable('lesson_calendar'), readTable('nutrition_plan'), readTable('sport_schedule'), readTable('dynamic_exams'), readTable('daily_tracking')]); if (!active) return; setProfile(p.data[0] ?? null); setExams(e.data); setTracking(t.data); if (l.data.length) setLessons(l.data.map(r => ({ day_of_week: asNum(r, 'day_of_week') as Day, title: asString(r, 'title', 'name', 'subject') ?? 'Attività di studio', start_time: asString(r, 'start_time', 'starts_at') ?? '', end_time: asString(r, 'end_time', 'ends_at') ?? '', mode: asString(r, 'mode', 'location_type', 'type') ?? 'Modalità non indicata' }))); if (s.data.length) setSports(s.data.map(r => ({ day_of_week: asNum(r, 'day_of_week') as Day, title: asString(r, 'title', 'sport', 'activity') ?? 'Attività sportiva', start_time: asString(r, 'start_time'), end_time: asString(r, 'end_time'), location: asString(r, 'location', 'place') ?? 'Luogo non indicato', min_duration: asNum(r, 'min_duration', 'duration_minutes'), intensity: asString(r, 'intensity') ?? 'Non indicata', required: Boolean(r.required ?? r.is_required ?? true), notes: asString(r, 'notes') ?? '' }))); if (n.data.length) { const next = { ...previewMeals }; n.data.forEach(r => { const d = asNum(r, 'day_of_week') as Day; const type = (asString(r, 'meal_type', 'type') ?? 'Pasto') as Meal['meal_type']; next[d] = [...(next[d] ?? []), { meal_type: type, meal_name: asString(r, 'meal_name', 'name', 'description') ?? 'Pasto senza descrizione' }] }); setMeals(next) } })(); return () => { active = false } }, [session])
  const timezone = asString(profile ?? {}, 'timezone') ?? 'Europe/Rome'; const dateLabel = new Intl.DateTimeFormat('it-IT', { weekday: 'long', day: 'numeric', month: 'long', timeZone: timezone }).format(new Date()); const currentLessons = lessons.filter(x => x.day_of_week === day); const currentSports = sports.filter(x => x.day_of_week === day); const currentMeals = meals[day] ?? []
  async function sendMagicLink(e: React.FormEvent) { e.preventDefault(); if (!supabase) return; setMessage('Invio del link in corso…'); const { error } = await supabase.auth.signInWithOtp({ email }); setMessage(error ? `Accesso non riuscito: ${error.message}` : 'Controlla la tua email per il link di accesso.') }
  async function logout() { await supabase?.auth.signOut(); setSession(null) }
  if (loading) return <div className="center-page"><div className="loader">Caricamento GoodHabit…</div></div>
  if (isSupabaseConfigured && !session) return <main className="center-page"><section className="login-card"><div className="brand-mark">G</div><p className="eyebrow">IL TUO RITMO, OGNI GIORNO</p><h1>Benvenuto in GoodHabit</h1><p className="muted">Accedi per vedere i tuoi impegni, i pasti e i progressi personali.</p><form onSubmit={sendMagicLink}><label>Email<input type="email" required value={email} onChange={e => setEmail(e.target.value)} placeholder="nome@email.it" /></label><button className="primary full">Ricevi il link di accesso</button></form>{message && <p className="notice">{message}</p>}</section></main>
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">G</div><div><strong>GoodHabit</strong><span>personal planner</span></div></div><nav>{tabs.map(item => <button key={item.id} className={tab === item.id ? 'nav-item active' : 'nav-item'} onClick={() => setTab(item.id)}><span>{item.icon}</span>{item.label}</button>)}</nav><div className="sidebar-bottom"><span className="status-dot" />{isSupabaseConfigured ? (session ? 'Connesso a Supabase' : 'Non autenticato') : 'Modalità anteprima'}{session && <button className="text-button" onClick={logout}>Esci</button>}</div></aside><main className="main"><header className="topbar"><div><p className="eyebrow">{tab === 'oggi' ? 'PANORAMICA DELLA GIORNATA' : 'GOODHABIT'}</p><h1>{tabs.find(x => x.id === tab)?.label}</h1></div><div className="date-pill">◷ {dateLabel}</div></header>{!isSupabaseConfigured && <div className="preview-banner"><span>Anteprima locale</span> I dati mostrati sono esempi del piano settimanale e non vengono salvati su Supabase.</div>}{tab === 'oggi' && <Dashboard day={day} dateLabel={dateLabel} lessons={currentLessons} meals={currentMeals} sports={currentSports} profile={profile} tracking={tracking} />}{tab === 'calendario' && <CalendarView day={day} setDay={setDay} lessons={lessons} sports={sports} />}{tab === 'alimentazione' && <MealsView day={day} setDay={setDay} meals={meals} />}{tab === 'allenamenti' && <SportsView day={day} setDay={setDay} sports={sports} />}{tab === 'esami' && <ExamsView exams={exams} />}{tab === 'progressi' && <ProgressView profile={profile} tracking={tracking} />}</main></div>
}
function DayPicker({ day, setDay }: { day: Day; setDay: (d: Day) => void }) { return <div className="day-picker">{dayNames.map((name, i) => <button key={name} className={day === i ? 'selected' : ''} onClick={() => setDay(i as Day)}><span>{name.slice(0, 3)}</span><b>{i}</b></button>)}</div> }
function Dashboard({ day, dateLabel, lessons, meals, sports, profile, tracking }: { day: Day; dateLabel: string; lessons: Lesson[]; meals: Meal[]; sports: Sport[]; profile: DbRow | null; tracking: DbRow[] }) { return <><section className="hero"><div><p className="eyebrow">{dateLabel}</p><h2>Un passo alla volta.</h2><p className="muted">Ecco cosa c’è in programma per te oggi.</p></div><div className="hero-orb">✦</div></section><div className="stat-grid"><Stat label="Livello" value={asString(profile ?? {}, 'avatar_level') ?? '—'} icon="↗" /><Stat label="Esperienza" value={profile ? `${asNum(profile, 'total_exp')} XP` : '—'} icon="✧" /><Stat label="Streak" value={profile ? `${asNum(profile, 'current_streak')} giorni` : '—'} icon="♨" /><Stat label="Check-in" value={tracking.length ? 'Disponibile' : 'Non registrato'} icon="✓" /></div><div className="section-heading"><div><p className="eyebrow">IL TUO GIORNO</p><h2>Agenda di oggi</h2></div><span className="small-note">I dati sono di sola lettura</span></div><div className="content-grid"><Card title="Studio" icon="▦">{lessons.length ? lessons.map((x, i) => <Timeline key={i} time={`${x.start_time} – ${x.end_time}`} title={x.title} tag={x.mode} />) : <Empty text="Nessuna lezione registrata." />}</Card><Card title="Pasti" icon="◒">{meals.map((x, i) => <div className="meal-row" key={i}><span className="meal-icon">{x.meal_type === 'Colazione' ? '☼' : x.meal_type === 'Pranzo' ? '◌' : '◍'}</span><div><small>{x.meal_type}</small><strong>{x.meal_name}</strong></div></div>)}{!meals.length && <Empty text="Nessun pasto registrato." />}</Card><Card title="Movimento" icon="↗">{sports.length ? sports.map((x, i) => <Timeline key={i} time={x.start_time ? `${x.start_time}${x.end_time ? ` – ${x.end_time}` : ''}` : 'Orario non disponibile'} title={x.title} tag={x.required ? 'Obbligatorio' : 'Facoltativo'} />) : <Empty text="Nessuna attività sportiva registrata." />}</Card></div></> }
function Stat({ label, value, icon }: { label: string; value: string; icon: string }) { return <div className="stat"><span className="stat-icon">{icon}</span><div><small>{label}</small><strong>{value}</strong></div></div> }
function Card({ title, icon, children }: { title: string; icon: string; children: React.ReactNode }) { return <section className="card"><div className="card-title"><h3><span>{icon}</span>{title}</h3><span className="more">···</span></div>{children}</section> }
function Timeline({ time, title, tag }: { time: string; title: string; tag: string }) { return <div className="timeline"><div className="timeline-time">{time}</div><div className="timeline-line" /><div><strong>{title}</strong><span className="tag">{tag}</span></div></div> }
function Empty({ text }: { text: string }) { return <div className="empty">{text}</div> }
function CalendarView({ day, setDay, lessons, sports }: { day: Day; setDay: (d: Day) => void; lessons: Lesson[]; sports: Sport[] }) { return <><DayPicker day={day} setDay={setDay} /><div className="section-heading"><div><p className="eyebrow">{dayNames[day]}</p><h2>Impegni programmati</h2></div></div><div className="content-grid two"><Card title="Studio e lezioni" icon="▦">{lessons.filter(x => x.day_of_week === day).map((x, i) => <Timeline key={i} time={`${x.start_time} – ${x.end_time}`} title={x.title} tag={x.mode} />)}{!lessons.some(x => x.day_of_week === day) && <Empty text="Nessuna lezione registrata per questo giorno." />}</Card><Card title="Sport" icon="↗">{sports.filter(x => x.day_of_week === day).map((x, i) => <Timeline key={i} time={x.start_time ? `${x.start_time}${x.end_time ? ` – ${x.end_time}` : ''}` : 'Orario non disponibile'} title={x.title} tag={x.required ? 'Obbligatorio' : 'Facoltativo'} />)}{!sports.some(x => x.day_of_week === day) && <Empty text="Nessuna attività sportiva registrata." />}</Card></div></> }
function MealsView({ day, setDay, meals }: { day: Day; setDay: (d: Day) => void; meals: Record<Day, Meal[]> }) { return <><DayPicker day={day} setDay={setDay} /><div className="section-heading"><div><p className="eyebrow">PIANO ALIMENTARE</p><h2>{dayNames[day]}</h2></div><span className="small-note">Nessun consiglio nutrizionale</span></div><div className="meal-list">{(meals[day] ?? []).map((m, i) => <article className="meal-card" key={i}><div className="meal-card-top"><span className="meal-icon large">{m.meal_type === 'Colazione' ? '☼' : m.meal_type === 'Pranzo' ? '◌' : '◍'}</span><div><p className="eyebrow">{m.meal_type}</p><h3>{m.meal_name}</h3></div></div>{m.details ? <div className="details">{Object.entries(m.details).map(([k, v]) => <span key={k}>{k}: <b>{v}</b></span>)}</div> : <p className="muted">Dettagli e quantità non disponibili.</p>}</article>)}{!(meals[day] ?? []).length && <Empty text="Nessun pasto registrato per questo giorno." />}<p className="small-note">Gli spuntini non risultano registrati.</p></div></> }
function SportsView({ day, setDay, sports }: { day: Day; setDay: (d: Day) => void; sports: Sport[] }) { return <><DayPicker day={day} setDay={setDay} /><div className="sport-list">{sports.filter(x => x.day_of_week === day).map((x, i) => <article className="sport-card" key={i}><div><span className="sport-symbol">↗</span><div><span className={x.required ? 'tag required' : 'tag optional'}>{x.required ? 'Obbligatorio' : 'Facoltativo'}</span><h3>{x.title}</h3></div></div><div className="sport-meta"><span>◷ {x.start_time ? `${x.start_time}${x.end_time ? ` – ${x.end_time}` : ''}` : 'Orario non disponibile'}</span><span>⌁ almeno {x.min_duration} min</span><span>⌖ {x.location}</span><span>Intensità {x.intensity.toLowerCase()}</span></div>{x.notes && <p className="muted">{x.notes}</p>}<div className="read-only">Solo consultazione · completamento non registrato</div></article>)}{!sports.some(x => x.day_of_week === day) && <Empty text="Nessuna attività sportiva registrata per questo giorno." />}</div></> }
function ExamsView({ exams }: { exams: DbRow[] }) { return <><div className="section-heading"><div><p className="eyebrow">STUDIO ED ESAMI</p><h2>I tuoi esami</h2></div><span className="small-note">Dati da dynamic_exams</span></div>{exams.length ? <div className="exam-grid">{exams.map((x, i) => <article className="exam-card" key={i}><span className="tag">{asString(x, 'status') ?? 'Stato non indicato'}</span><h3>{asString(x, 'name', 'title', 'subject') ?? 'Esame senza nome'}</h3><p className="muted">{asString(x, 'type') ?? 'Tipo non indicato'} · {asString(x, 'cfu') ? `${asString(x, 'cfu')} CFU` : 'CFU non indicati'}</p><p>{asString(x, 'exam_date', 'date') ?? 'Data non indicata'}</p></article>)}</div> : <div className="empty-panel"><span>□</span><h3>Nessun esame ancora</h3><p>Quando saranno presenti record in dynamic_exams, li vedrai qui.</p></div>}</> }
function ProgressView({ profile, tracking }: { profile: DbRow | null; tracking: DbRow[] }) { return <><div className="profile-hero"><div className="avatar">{asString(profile ?? {}, 'avatar_level') ?? '—'}</div><div><p className="eyebrow">PROFILO PERSONALE</p><h2>Il tuo percorso</h2><p className="muted">I valori vengono mostrati così come salvati nel database.</p></div></div><div className="stat-grid"><Stat label="Esperienza totale" value={profile ? `${asNum(profile, 'total_exp')} XP` : '—'} icon="✧" /><Stat label="Streak corrente" value={profile ? `${asNum(profile, 'current_streak')} giorni` : '—'} icon="♨" /><Stat label="Ultimo check-in" value={asString(profile ?? {}, 'last_check_in') ?? '—'} icon="✓" /></div><Card title="Check-in giornalieri" icon="✓">{tracking.length ? tracking.map((x, i) => <div className="tracking-row" key={i}><strong>{asString(x, 'tracked_date', 'date') ?? 'Data non indicata'}</strong><span>XP guadagnati: {asString(x, 'xp_earned') ?? '—'}</span><span>{x.day_completed ? 'Giornata completata' : 'Completamento non registrato'}</span></div>) : <Empty text="Nessun check-in registrato." />}</Card><p className="small-note block-note">XP, livello e streak non vengono calcolati dall’interfaccia.</p></> }
